steps:
  # 1. Create a Docker image containing hadoop-connectors repo
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--network=cloudbuild', '--tag=gcr.io/$PROJECT_ID/dataproc-spark-bigquery-connector-nightly', '-f', 'cloudbuild/Dockerfile', '.']

# 2. Fetch maven and dependencies
  - name: 'gcr.io/$PROJECT_ID/dataproc-spark-bigquery-connector-nightly'
    id: 'maven-build'
    entrypoint: 'bash'
    args: ['/workspace/cloudbuild/nightly.sh']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'
      - 'ACCEPTANCE_TEST_BUCKET=${_ACCEPTANCE_TEST_BUCKET}'
      - 'SERVERLESS_NETWORK_URI=${_SERVERLESS_NETWORK_URI}'
      - 'CODECOV_TOKEN=${_CODECOV_TOKEN}'
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        revision="$(cat /workspace/revision.txt)"
        gsutil cp "/workspace/.repository/com/google/cloud/spark/spark-bigquery-with-dependencies_2.11/$revision/spark-bigquery-with-dependencies_2.11-$revision.jar" gs://spark-lib-daily-snapshots
        gsutil cp "gs://spark-lib-daily-snapshots/spark-bigquery-with-dependencies_2.11-$revision.jar" gs://spark-lib-daily-snapshots/spark-bigquery-with-dependencies_2.11-daily-snapshot.jar
        gsutil cp "/workspace/.repository/com/google/cloud/spark/spark-bigquery-with-dependencies_2.12/$revision/spark-bigquery-with-dependencies_2.12-$revision.jar" gs://spark-lib-daily-snapshots
        gsutil cp "gs://spark-lib-daily-snapshots/spark-bigquery-with-dependencies_2.12-$revision.jar" gs://spark-lib-daily-snapshots/spark-bigquery-with-dependencies_2.12-daily-snapshot.jar
        gsutil cp "/workspace/.repository/com/google/cloud/spark/spark-2.4-bigquery/$revision-preview/spark-2.4-bigquery-$revision-preview.jar" gs://spark-lib-daily-snapshots
        gsutil cp "gs://spark-lib-daily-snapshots/spark-2.4-bigquery-$revision-preview.jar" gs://spark-lib-daily-snapshots/spark-2.4-bigquery-daily-snapshot-preview.jar
        

# Tests take around 20 mins in general.
timeout: 3600s

options:
  machineType: 'N1_HIGHCPU_32'
